### ISSUE TITLE
Wrong reactions scraped

### ISSUE THREAD

**Issue by y2kfresh** [kennethreitz/twitter-scraper#22]
E.g:

> 
>   for tweet in get_tweets('realDonaldTrump', pages=1):
> ...     print(tweet)
> ...
> 
>  {'text': 'Possible progress being made in talks with North Korea. For the first time in many years, a serious effort is being made by all parties concerned. The World is watching and waiting! May be false hope, but the U.S. is ready to go hard in either direction!', **'replies': 0, 'retweets': 0, 'likes': 0**}
> 

Source:
> Possible progress being made in talks with North Korea. For the first time in many years, a serious effort is being made by all parties concerned. The World is watching and waiting! May be false hope, but the U.S. is ready to go hard in either direction!
> **6,967 replies 10,161 retweets 38,094 likes**

**Comment by danielfr3** [comment]
Can I try to fix it?

**Comment by kennethreitz** [comment]
@danielfr3 go for it!

**Comment by y2kfresh** [comment]
@kennethreitz :  ty, it also need .replace(",","") or values greater than one thousand

**Comment by danielfr3** [comment]
I’ll do it!
