### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '2\xa0571

### ISSUE THREAD

**Issue by rbnali** [kennethreitz/twitter-scraper#37]
Hi,

I tried the example in your README file (USAGE), but I get the following error:

`ValueError: invalid literal for int() with base 10: '2\xa0571'`

Could you help me fix it?

Thanks

**Comment by georgeglessner** [comment]
If you do `print(tweet)` instead of `print(tweet['text'])` it should work as expected.

**Comment by dkillion** [comment]
Just installed via pipenv today and getting this error doing the example code:

>>> from twitter_scraper import get_tweets
>>> for tweet in get_tweets('kennethreitz', pages=1):
...  print(tweet['text'])
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dkillion/.local/share/virtualenvs/dkillion-HGOF7GqZ/lib/python3.6/site-packages/twitter_scraper.py", line 78, in get_tweets
    yield from gen_tweets(pages)
  File "/home/dkillion/.local/share/virtualenvs/dkillion-HGOF7GqZ/lib/python3.6/site-packages/twitter_scraper.py", line 42, in gen_tweets
    replies = int(interactions[0].split(" ")[0].replace(comma, "").replace(dot,""))
ValueError: invalid literal for int() with base 10: '\\n'

**Comment by spiw** [comment]
![image](https://user-images.githubusercontent.com/18377668/44145796-b428a350-a095-11e8-8f9f-76c7e0155d07.png)
Same issue here

**Comment by spiw** [comment]
@rbnali  @dkillion,
for temporary solution you can go to corresponding twitter_scraper.py file and wrap problematic lines with try catch

Exmaple twitter_scraper.py path:  /Users/username/.local/share/virtualenvs/project-name/lib/python3.7/site-packages/twitter_scraper.py

Replace the lines:
`                replies = int(interactions[0].split(" ")[0].replace(comma, "").replace(dot,""))
                retweets = int(interactions[1].split(" ")[
                               0].replace(comma, "").replace(dot,""))`

with
`                try:
                    replies = int(interactions[0].split(" ")[0].replace(comma, "").replace(dot, ""))
                except ValueError:
                    replies = 0

                try:
                    retweets = int(interactions[1].split(" ")[
                                       0].replace(comma, "").replace(dot, ""))
                except ValueError:
                    retweets = 0`

if you are having problem, you can do the same thing for likes.
