### ISSUE TITLE
Add in random wait, random user agent, and ability to pass in proxy ip address.

### ISSUE THREAD

**Issue by jamesacampbell** [kennethreitz/twitter-scraper#4]
Not sure how far you want to go to obfuscate your collection efforts here from twitter powers that be, but would be really cool to implement these things. Want me to fork and do a pull request? What is the contribution guide? Is that the direction you want to take this?

**Comment by jamesacampbell** [comment]
Btw, this is awesome. Twitter used to be so friendly to developers and completely open in their usage to allow devs to build apps, but has been frustratingly locked down so much.

**Comment by jamesacampbell** [comment]
For user agent randomization, I would use the great `fake-useragent`: https://github.com/hellysmile/fake-useragent

**Comment by kennethreitz** [comment]
I like the fake user agent idea!
