### ISSUE TITLE
Get likes and retweets

### ISSUE THREAD

**Issue by yemen2016** [kennethreitz/twitter-scraper#40]
Hi,
I would like to extract likes and retweets against all tweets.
Please help...

**Comment by Recursing** [comment]
I think this project has been abandoned, you should use a different one

**Comment by ferguras** [comment]
You could use my fork at https://github.com/ferguras/twitter-analysis
It has an boolean parameter that allows you to select if you want to have retweets collected or not. And it collects the original sender of the tweet.
