### ISSUE TITLE
IndexError for tweet text class

### ISSUE THREAD

**Issue by kwakueshun** [kennethreitz/twitter-scraper#49]
Hello, I noticed an `IndexError: list index out of range` error coming from this line sometimes:  
```python 
text = tweet.find('.tweet-text')[0].full_text
```

**Comment by atonn** [comment]
I tried to look into it, but couldn't wrap my head around it. Sometimes non-tweet elements seem to sneak in between the "tweets" returned by html.find('.stream-item'). 

So as a personal quick fix,

try:
	text = tweet.find('.tweet-text')[0].full_text
except Exception:
	continue

works fine for now and does not appear to skip any tweets.

**Comment by kwakueshun** [comment]
I can confirm that this fix worked for my use case. Thanks
