### ISSUE TITLE
Breaking with new Twitter update

### ISSUE THREAD

**Issue by shelsoloa** [kennethreitz/twitter-scraper#56]
Since the latest twitter update, I have been encountering multiple errors. I think it's related to the new  html on twitter pages, the scraper probably needs to be reconfigured

**Comment by theaupoulat** [comment]
Hey! Can you provide some examples ? Thanks :)

**Comment by bisguzar** [comment]
Tests still working without any error. Please open more spesific issue, thanks for attention
